language: rust
sudo: false
rust:
  - nightly

os:
  - linux
  - osx

before_script:
    - export PATH=$HOME/.local/bin:/Users/travis/Library/Python/2.7/bin:$PATH
    - pip install servo_tidy --user `whoami`

script:
    - servo-tidy

notifications:
  webhooks: http://build.servo.org:54856/travis
